/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmi_client;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author hp
 */
public class managetransportation extends javax.swing.JFrame {

    /**
     * Creates new form managetransportation
     */
    public managetransportation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1TransportationManagerID = new javax.swing.JTextField();
        jTextField2TransportationManagerTYPE = new javax.swing.JTextField();
        jTextField3TransportationManagerLOC = new javax.swing.JTextField();
        jTextField4TransportationManagerDURA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1TransportationManagerPOST = new javax.swing.JButton();
        jButton2TransportationManagerEDITE = new javax.swing.JButton();
        jLabel6TransportationManagerSUCESS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1TransportationManagerID.setText("Enter ID");

        jTextField2TransportationManagerTYPE.setText("Enter transportation type");
        jTextField2TransportationManagerTYPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2TransportationManagerTYPEActionPerformed(evt);
            }
        });

        jTextField3TransportationManagerLOC.setText("Enter the location");
        jTextField3TransportationManagerLOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3TransportationManagerLOCActionPerformed(evt);
            }
        });

        jTextField4TransportationManagerDURA.setText("Enter number of days");

        jLabel1.setText("ID");

        jLabel2.setText("Transportation Type");

        jLabel3.setText("Location");

        jLabel4.setText("Duration per day");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Transportation Manager");

        jButton1TransportationManagerPOST.setText("Post");
        jButton1TransportationManagerPOST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1TransportationManagerPOSTActionPerformed(evt);
            }
        });

        jButton2TransportationManagerEDITE.setText("Edite");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1TransportationManagerID)
                    .addComponent(jTextField2TransportationManagerTYPE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(jTextField3TransportationManagerLOC, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4TransportationManagerDURA, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1TransportationManagerPOST)
                                .addGap(111, 111, 111)
                                .addComponent(jButton2TransportationManagerEDITE))
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel6TransportationManagerSUCESS, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1TransportationManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2TransportationManagerTYPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3TransportationManagerLOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4TransportationManagerDURA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(55, 55, 55)
                .addComponent(jLabel6TransportationManagerSUCESS, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1TransportationManagerPOST)
                    .addComponent(jButton2TransportationManagerEDITE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3TransportationManagerLOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3TransportationManagerLOCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3TransportationManagerLOCActionPerformed

    private void jTextField2TransportationManagerTYPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2TransportationManagerTYPEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2TransportationManagerTYPEActionPerformed

    private void jButton1TransportationManagerPOSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1TransportationManagerPOSTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1TransportationManagerPOSTActionPerformed

      public JTextField getjTextField1TransportationManagerID() {
        return jTextField1TransportationManagerID;
    }
     public JTextField getjTextField2TransportationManagerTYPE() {
        return jTextField2TransportationManagerTYPE;
    }
 public JTextField getjTextField3TransportationManagerLOC() {
        return jTextField3TransportationManagerLOC;
    }
  public JTextField getjTextField4TransportationManagerDURA() {
        return jTextField4TransportationManagerDURA;
    }
   
   public JButton getjButton1TransportationManagerPOST() {
        return jButton1TransportationManagerPOST;
    }
   
   public JButton getjButton2TransportationManagerEDITE() {
        return jButton2TransportationManagerEDITE;
    }
   public JLabel getjLabel6TransportationManagerSUCESS(){
   
       return jLabel6TransportationManagerSUCESS;
   
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1TransportationManagerPOST;
    private javax.swing.JButton jButton2TransportationManagerEDITE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6TransportationManagerSUCESS;
    private javax.swing.JTextField jTextField1TransportationManagerID;
    private javax.swing.JTextField jTextField2TransportationManagerTYPE;
    private javax.swing.JTextField jTextField3TransportationManagerLOC;
    private javax.swing.JTextField jTextField4TransportationManagerDURA;
    // End of variables declaration//GEN-END:variables
}
